#rest server
server.port: 8888

#logging
logging.level:
#  root: DEBUG
  org:
    springframework:
      boot:
        web: INFO
      data.r2dbc: INFO
  io.r2dbc: INFO

#database
spring:
  main:
    lazy-initialization: true
  h2:
    console.enabled: true
  r2dbc:
    url: 'r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1'
    pool:
      initial-size: 10
      max-size: 10
      validation-query: SELECT 1
  cache:
    cache-names: products
    caffeine.spec: maximumSize=500,expireAfterAccess=5000s

#api
product:
  api:
    client: http://localhost:8888